Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -46,8 +46,8 @@ jobs:
       - name: Terraform Plan
         id: plan
         run: terraform plan -no-color
-        if: github.event_name == 'pull_request'
-        continue-on-error: true
+#         if: github.event_name == 'pull_request'
+#         continue-on-error: true
 
 #       - uses: actions/github-script@v6
 #         if: github.event_name == 'pull_request'
@@ -77,9 +77,9 @@ jobs:
 #               repo: context.repo.repo,
 #               body: output
 #             })
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+#       - name: Terraform Plan Status
+#         if: steps.plan.outcome == 'failure'
+#         run: exit 1
 
       - name: Terraform Apply
         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
